from core.event_definition import EventDefinition
from core.models import (
    CompanyCourse as CC,
    ConditionSignal as CS,
    FreeActionKind as FA,
    RelationshipSignal as RS,
    SkillId as SK,
)
from core.events.common import (
    D, I, L, MINOR, N, P, RELATIONSHIP, ROSTER, SLOT, TRAINEE,
    all_of, any_of, any_skill_unlocked, bound_relationship, choice,
    company_course, company_skill_course, company_slot, condition_any,
    condition_effect, condition_range, free_action, free_slot, month_end_within,
    relationship_effect, skill_unlocked, slot_index, slot_index_below,
)


SOCIAL = free_action(FA.SOCIAL)
BREAK = free_action(FA.RECOVER, FA.PERSONAL)


TRAINEE_SOCIAL_EVENTS = (
    # 061 social_trainee_first_name_exchange
    EventDefinition(event_id="social_trainee_first_name_exchange", category=RELATIONSHIP, trigger_mode=D, tier=MINOR, interaction_mode=N, priority=30, once=True, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=bound_relationship(familiarity_max=5), effects=(relationship_effect(RS.CASUAL_CONTACT),), director_brief="The selected trainee introduces herself properly for the first time."),
    # 062 social_trainee_first_shared_wait
    EventDefinition(event_id="social_trainee_first_shared_wait", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.24, priority=10, once=True, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=all_of(company_slot, bound_relationship(familiarity_max=25)), director_brief="The selected trainee happens to wait beside the player before leaving."),
    # 063 social_trainee_first_practice_question
    EventDefinition(event_id="social_trainee_first_practice_question", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.22, priority=10, once=True, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=all_of(company_slot, bound_relationship(familiarity_max=25)), director_brief="The selected trainee asks what the player practiced in the completed slot."),
    # 064 social_trainee_first_seat_share
    EventDefinition(event_id="social_trainee_first_seat_share", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.20, priority=10, once=True, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=all_of(free_slot, bound_relationship(familiarity_max=25)), director_brief="Limited seating places the selected trainee beside the player."),
    # 065 social_trainee_first_route_overlap
    EventDefinition(event_id="social_trainee_first_route_overlap", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.18, priority=10, once=True, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=all_of(slot_index(0, 7), bound_relationship(familiarity_max=25)), director_brief="A short part of the selected trainee's route overlaps with the player's."),
    # 066 social_trainee_first_schedule_compare
    EventDefinition(event_id="social_trainee_first_schedule_compare", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.20, priority=10, once=True, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=all_of(company_slot, bound_relationship(familiarity_max=25)), director_brief="The selected trainee briefly compares the next posted course with the player."),
    # 067 social_trainee_acquaintance_greeting
    EventDefinition(event_id="social_trainee_acquaintance_greeting", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.24, priority=10, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=bound_relationship(familiarity_min=6), director_brief="The selected trainee greets the player without needing an introduction."),
    # 068 social_trainee_acquaintance_name_recall
    EventDefinition(event_id="social_trainee_acquaintance_name_recall", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.16, priority=10, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=bound_relationship(familiarity_min=6), director_brief="The selected trainee remembers a small practical detail from an earlier exchange."),
    # 069 social_trainee_acquaintance_course_chat
    EventDefinition(event_id="social_trainee_acquaintance_course_chat", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.22, priority=10, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, bound_relationship(familiarity_max=50)), effects=(relationship_effect(RS.CASUAL_CONTACT),), director_brief="They compare one ordinary detail from recent classes."),
    # 070 social_trainee_acquaintance_shared_joke
    EventDefinition(event_id="social_trainee_acquaintance_shared_joke", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.16, priority=10, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, condition_range("mood", 25)), effects=(relationship_effect(RS.SHARED_POSITIVE_EXPERIENCE),), director_brief="A small joke about the immediate situation lands between them."),
    # 071 social_trainee_acquaintance_quiet_company
    EventDefinition(event_id="social_trainee_acquaintance_quiet_company", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.17, priority=10, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, bound_relationship(familiarity_min=10)), effects=(relationship_effect(RS.CASUAL_CONTACT),), director_brief="They spend part of the social slot together without much conversation."),
    # 072 social_trainee_acquaintance_update
    EventDefinition(event_id="social_trainee_acquaintance_update", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.19, priority=10, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=all_of(company_slot, bound_relationship(familiarity_min=10)), effects=(relationship_effect(RS.RELIABILITY_CONFIRMED),), director_brief="The selected trainee passes along a minor posted schedule detail."),
    # 073 social_trainee_acquaintance_leave_together
    EventDefinition(event_id="social_trainee_acquaintance_leave_together", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.18, priority=10, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=all_of(slot_index(7), bound_relationship(familiarity_min=10)), director_brief="The selected trainee leaves the room at the same time as the player."),
    # 074 social_trainee_shared_count_check
    EventDefinition(event_id="social_trainee_shared_count_check", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.20, priority=10, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, any_of(skill_unlocked(SK.DANCE), skill_unlocked(SK.STAGE))), effects=(relationship_effect(RS.SHARED_POSITIVE_EXPERIENCE),), director_brief="They check a short count sequence together."),
    # 075 social_trainee_shared_stretch_space
    EventDefinition(event_id="social_trainee_shared_stretch_space", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.18, priority=10, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=SOCIAL, effects=(relationship_effect(RS.CASUAL_CONTACT),), director_brief="Limited stretch space leads the two to coordinate turns."),
    # 076 social_trainee_shared_playback
    EventDefinition(event_id="social_trainee_shared_playback", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.16, priority=10, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, skill_unlocked(SK.CAMERA)), effects=(relationship_effect(RS.SHARED_POSITIVE_EXPERIENCE),), director_brief="A short scene-local playback gives them one detail to compare."),
    # 077 social_trainee_shared_lyrics_prompt
    EventDefinition(event_id="social_trainee_shared_lyrics_prompt", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.17, priority=10, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, any_skill_unlocked(SK.VOCAL, SK.RAP, SK.LANGUAGE)), effects=(relationship_effect(RS.SHARED_POSITIVE_EXPERIENCE),), director_brief="They prompt each other through practice lines introduced by the event."),
    # 078 social_trainee_shared_timing_reset
    EventDefinition(event_id="social_trainee_shared_timing_reset", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.19, priority=10, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, bound_relationship(familiarity_min=10)), effects=(relationship_effect(RS.RELIABILITY_CONFIRMED),), director_brief="A timing mismatch is reset calmly without assigning blame."),
    # 079 social_trainee_shared_mirror_turns
    EventDefinition(event_id="social_trainee_shared_mirror_turns", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.18, priority=10, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, any_skill_unlocked(SK.DANCE, SK.STAGE)), effects=(relationship_effect(RS.CASUAL_CONTACT),), director_brief="They take turns using the clearest mirror space."),
    # 080 social_trainee_shared_end_review
    EventDefinition(event_id="social_trainee_shared_end_review", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.17, priority=10, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, bound_relationship(familiarity_min=10)), effects=(relationship_effect(RS.SHARED_POSITIVE_EXPERIENCE),), director_brief="Before separating, each names one part to revisit later."),
    # 081 social_trainee_shared_slow_run
    EventDefinition(event_id="social_trainee_shared_slow_run", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.16, priority=10, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, any_skill_unlocked()), effects=(relationship_effect(RS.SHARED_POSITIVE_EXPERIENCE),), director_brief="They complete one deliberately slow practice run together."),
    # 082 social_trainee_meal_queue_chat
    EventDefinition(event_id="social_trainee_meal_queue_chat", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.22, priority=10, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=BREAK, director_brief="The selected trainee talks briefly with the player in a food queue."),
    # 083 social_trainee_table_space
    EventDefinition(event_id="social_trainee_table_space", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.20, priority=10, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=BREAK, director_brief="The selected trainee makes room at a partly occupied table."),
    # 084 social_trainee_drink_recommendation
    EventDefinition(event_id="social_trainee_drink_recommendation", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.17, priority=10, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=BREAK, director_brief="The selected trainee offers a practical drink recommendation."),
    # 085 social_trainee_short_break_walk
    EventDefinition(event_id="social_trainee_short_break_walk", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.16, priority=10, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=SOCIAL, effects=(relationship_effect(RS.SHARED_POSITIVE_EXPERIENCE),), director_brief="They walk a short indoor loop during the social slot."),
    # 086 social_trainee_snack_split
    EventDefinition(event_id="social_trainee_snack_split", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.15, priority=10, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, bound_relationship(familiarity_min=10)), effects=(relationship_effect(RS.SHARED_POSITIVE_EXPERIENCE),), director_brief="A snack present in the scene is split between them."),
    # 087 social_trainee_meal_silence
    EventDefinition(event_id="social_trainee_meal_silence", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.15, priority=10, cooldown_days=2, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, condition_any(condition_range("mood", 0, 34), condition_range("stress", 50))), effects=(relationship_effect(RS.CASUAL_CONTACT),), director_brief="They eat together with little conversation and no obvious conflict."),
    # 088 social_trainee_break_cut_short
    EventDefinition(event_id="social_trainee_break_cut_short", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.14, priority=10, cooldown_days=2, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, slot_index_below(7)), effects=(relationship_effect(RS.CASUAL_CONTACT),), director_brief="The next canonical slot cuts their shared break short."),
    # 089 social_trainee_lend_hair_tie
    EventDefinition(event_id="social_trainee_lend_hair_tie", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.15, priority=10, cooldown_days=4, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=bound_relationship(familiarity_min=10), effects=(relationship_effect(RS.RELIABILITY_CONFIRMED),), director_brief="The selected trainee asks for a small practical item present in the scene."),
    # 090 social_trainee_hold_place
    EventDefinition(event_id="social_trainee_hold_place", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.15, priority=10, cooldown_days=4, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=BREAK, effects=(relationship_effect(RS.RELIABILITY_CONFIRMED),), director_brief="The selected trainee asks the player to hold a place in a short queue."),
    # 091 social_trainee_message_schedule
    EventDefinition(event_id="social_trainee_message_schedule", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.16, priority=10, cooldown_days=4, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=all_of(company_slot, bound_relationship(familiarity_min=10)), effects=(relationship_effect(RS.RELIABILITY_CONFIRMED),), director_brief="The player relays a posted course reminder to the selected trainee."),
    # 092 social_trainee_find_charger
    EventDefinition(event_id="social_trainee_find_charger", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.13, priority=10, cooldown_days=5, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=free_slot, director_brief="The selected trainee and player locate a charger present in the rest area."),
    # 093 social_trainee_check_room_board
    EventDefinition(event_id="social_trainee_check_room_board", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.18, priority=10, cooldown_days=3, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=company_slot, effects=(relationship_effect(RS.RELIABILITY_CONFIRMED),), director_brief="They verify the current canonical course room together before separating."),
    # 094 social_trainee_carry_light_items
    EventDefinition(event_id="social_trainee_carry_light_items", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.13, priority=10, cooldown_days=5, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=SOCIAL, effects=(relationship_effect(RS.SHARED_POSITIVE_EXPERIENCE),), director_brief="They carry a few light practice items present in the scene."),
    # 095 social_trainee_wait_for_lace
    EventDefinition(event_id="social_trainee_wait_for_lace", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=N, base_probability=.16, priority=10, cooldown_days=3, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=SOCIAL, effects=(relationship_effect(RS.RELIABILITY_CONFIRMED),), director_brief="The selected trainee waits while the player fixes a small clothing issue."),
    # 096 social_trainee_awkward_name_mixup
    EventDefinition(event_id="social_trainee_awkward_name_mixup", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.42, priority=20, cooldown_days=12, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=bound_relationship(familiarity_max=50), director_brief="The selected trainee makes a small name or detail mix-up.", choices=(choice("correct_lightly", "轻松地纠正一下"), choice("move_past_mixup", "不在意这件小事，继续聊"))),
    # 097 social_trainee_awkward_interruption
    EventDefinition(event_id="social_trainee_awkward_interruption", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.50, priority=20, cooldown_days=5, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=bound_relationship(familiarity_min=6), director_brief="The selected trainee and player begin speaking at the same time.", choices=(choice("laugh_and_restart", "笑一下，重新说"), choice("invite_trainee_continue", "让对方先说完"))),
    # 098 social_trainee_awkward_empty_seat
    EventDefinition(event_id="social_trainee_awkward_empty_seat", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.42, priority=20, cooldown_days=7, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=BREAK, director_brief="It is unclear whether the seat beside the selected trainee is reserved.", choices=(choice("ask_before_sitting", "先问一下再坐"), choice("choose_another_seat", "换到旁边另一个位置"))),
    # 099 social_trainee_awkward_missed_greeting
    EventDefinition(event_id="social_trainee_awkward_missed_greeting", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.38, priority=20, cooldown_days=8, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=bound_relationship(familiarity_max=50), director_brief="The selected trainee may not have noticed the player's greeting.", choices=(choice("circle_back_and_greet", "回过头再打个招呼", relationship_effect(RS.REPAIR), condition_effect(CS.STRESS_RELIEF)), choice("leave_for_next_time", "这次先算了，下次再说", relationship_effect(RS.CASUAL_CONTACT), condition_effect(CS.MOOD_HIT)))),
    # 100 social_trainee_awkward_wrong_assumption
    EventDefinition(event_id="social_trainee_awkward_wrong_assumption", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.38, priority=20, cooldown_days=9, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=all_of(company_slot, bound_relationship(familiarity_min=6)), director_brief="The player makes a harmless wrong assumption about the selected trainee's next task.", choices=(choice("acknowledge_mixup", "承认自己弄错了", relationship_effect(RS.CASUAL_CONTACT), condition_effect(CS.MOOD_LIFT)), choice("redirect_to_schedule", "把话题转回实际安排", relationship_effect(RS.CASUAL_CONTACT), condition_effect(CS.STRESS_RELIEF)))),
    # 101 social_trainee_awkward_quiet_gap
    EventDefinition(event_id="social_trainee_awkward_quiet_gap", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.50, priority=20, cooldown_days=5, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, bound_relationship(tension_max=69)), director_brief="The active social conversation reaches an uncertain quiet gap.", choices=(choice("let_pause_stand", "就让这段安静继续一会儿", relationship_effect(RS.CASUAL_CONTACT), condition_effect(CS.STRESS_RELIEF)), choice("introduce_light_topic", "换个轻松的话题", relationship_effect(RS.SHARED_POSITIVE_EXPERIENCE), condition_effect(CS.MOOD_LIFT)))),
    # 102 social_trainee_competitive_extra_run
    EventDefinition(event_id="social_trainee_competitive_extra_run", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.44, priority=20, cooldown_days=7, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, any_skill_unlocked(), bound_relationship(trust_min=5)), director_brief="The selected SOCIAL trainee proposes comparing one practice run.", choices=(choice("join_comparison_run", "一起比一遍看看", relationship_effect(RS.SHARED_POSITIVE_EXPERIENCE), condition_effect(CS.CONFIDENCE_GAIN)), choice("keep_noncomparative", "不比较，各练各的", relationship_effect(RS.CASUAL_CONTACT), condition_effect(CS.STRESS_RELIEF)))),
    # 103 social_trainee_competitive_score_talk
    EventDefinition(event_id="social_trainee_competitive_score_talk", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.40, priority=20, cooldown_days=8, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, month_end_within(7)), director_brief="The selected SOCIAL trainee asks how the player thinks training is going.", choices=(choice("answer_cautiously", "简单保守地回答", relationship_effect(RS.CASUAL_CONTACT), condition_effect(CS.STRESS_RELIEF)), choice("share_self_assessment", "坦白说说自己的感觉", relationship_effect(RS.SHARED_POSITIVE_EXPERIENCE), condition_effect(CS.CONFIDENCE_GAIN)))),
    # 104 social_trainee_competitive_front_position
    EventDefinition(event_id="social_trainee_competitive_front_position", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.42, priority=20, cooldown_days=7, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=company_course(CC.DANCE, CC.STAGE), director_brief="The selected trainee and player consider the same visible practice position.", choices=(choice("suggest_alternating", "提议轮流站这个位置", relationship_effect(RS.CASUAL_CONTACT), condition_effect(CS.STRESS_RELIEF)), choice("take_position_this_run", "这一遍自己站这个位置", relationship_effect(RS.SHARED_POSITIVE_EXPERIENCE), condition_effect(CS.CONFIDENCE_GAIN)))),
    # 105 social_trainee_competitive_good_day
    EventDefinition(event_id="social_trainee_competitive_good_day", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.46, priority=20, cooldown_days=6, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=all_of(company_skill_course, bound_relationship(tension_max=69)), director_brief="The selected trainee has a notably smooth run in the same practice setting.", choices=(choice("acknowledge_strong_run", "直接夸一句她这一遍练得不错", relationship_effect(RS.SHARED_POSITIVE_EXPERIENCE), condition_effect(CS.MOOD_LIFT)), choice("keep_own_focus", "不打扰她，继续专注自己", relationship_effect(RS.CASUAL_CONTACT), condition_effect(CS.STRESS_RELIEF)))),
    # 106 social_trainee_competitive_comparison_comment
    EventDefinition(event_id="social_trainee_competitive_comparison_comment", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.34, priority=20, cooldown_days=10, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=all_of(company_skill_course, bound_relationship(tension_max=69)), director_brief="A neutral comparison comment to the selected trainee lands poorly.", choices=(choice("clarify_intent", "解释清楚自己的意思", relationship_effect(RS.REPAIR), condition_effect(CS.STRESS_RELIEF)), choice("let_comment_pass", "先不解释，让这句话过去", relationship_effect(RS.FRICTION), condition_effect(CS.MOOD_HIT)))),
    # 107 social_trainee_competitive_shared_goal
    EventDefinition(event_id="social_trainee_competitive_shared_goal", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.40, priority=20, cooldown_days=8, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, any_skill_unlocked(), bound_relationship(familiarity_min=35)), director_brief="The selected SOCIAL trainee suggests a small target for one shared run.", choices=(choice("agree_shared_target", "一起定一个小目标", relationship_effect(RS.RELIABILITY_CONFIRMED), condition_effect(CS.CONFIDENCE_GAIN)), choice("keep_separate_targets", "各自按自己的目标练", relationship_effect(RS.CASUAL_CONTACT), condition_effect(CS.STRESS_RELIEF)))),
    # 108 social_trainee_competitive_result_question
    EventDefinition(event_id="social_trainee_competitive_result_question", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.44, priority=20, cooldown_days=7, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, any_skill_unlocked()), director_brief="The selected SOCIAL trainee offers one scene-local peer observation.", choices=(choice("hear_observation", "听听她的一点意见", relationship_effect(RS.SHARED_POSITIVE_EXPERIENCE), condition_effect(CS.CONFIDENCE_GAIN)), choice("decline_feedback_now", "暂时不听反馈", relationship_effect(RS.CASUAL_CONTACT), condition_effect(CS.STRESS_RELIEF)))),
    # 109 social_trainee_misunderstood_schedule
    EventDefinition(event_id="social_trainee_misunderstood_schedule", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.38, priority=20, cooldown_days=9, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=all_of(company_slot, bound_relationship(familiarity_min=6)), director_brief="The selected trainee and player recall the next posted course differently.", choices=(choice("check_schedule_together", "一起去确认正式安排", relationship_effect(RS.REPAIR), condition_effect(CS.STRESS_RELIEF)), choice("use_own_recollection", "先按自己的记忆来", relationship_effect(RS.FRICTION), condition_effect(CS.STRESS_INCREASE)))),
    # 110 social_trainee_misread_short_reply
    EventDefinition(event_id="social_trainee_misread_short_reply", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.34, priority=20, cooldown_days=12, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=bound_relationship(familiarity_min=35, interacted=True), director_brief="A short reply from the selected trainee is hard to read in tone.", choices=(choice("ask_if_okay", "问问她是不是有什么事", relationship_effect(RS.REPAIR), condition_effect(CS.STRESS_RELIEF)), choice("give_space", "先给她一点自己的空间", relationship_effect(RS.DISTANCING), condition_effect(CS.MOOD_HIT)))),
    # 111 social_trainee_shared_item_return_delay
    EventDefinition(event_id="social_trainee_shared_item_return_delay", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.32, priority=20, cooldown_days=14, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=bound_relationship(familiarity_min=35, trust_min=10), director_brief="A small promised practical favor from the selected trainee is delayed.", choices=(choice("mention_delay", "直接提一下这件事", relationship_effect(RS.REPAIR)), choice("accept_without_discussion", "不再追问，就这样算了", relationship_effect(RS.FRICTION)))),
    # 112 social_trainee_practice_space_overlap
    EventDefinition(event_id="social_trainee_practice_space_overlap", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.44, priority=20, cooldown_days=7, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=company_course(CC.DANCE, CC.STAGE), director_brief="The selected trainee and player reach for the same limited practice area.", choices=(choice("split_time", "把时间分开轮流用", relationship_effect(RS.RELIABILITY_CONFIRMED)), choice("use_another_area", "自己换个地方", relationship_effect(RS.CASUAL_CONTACT)))),
    # 113 social_trainee_unwanted_advice
    EventDefinition(event_id="social_trainee_unwanted_advice", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.36, priority=20, cooldown_days=10, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=all_of(condition_range("stress", 50), bound_relationship(familiarity_min=6)), director_brief="The selected trainee offers practical advice at a poor moment.", choices=(choice("ask_for_advice_later", "告诉她晚一点再聊建议", relationship_effect(RS.REPAIR)), choice("hear_with_limit", "先听，但明确自己只想听一点", relationship_effect(RS.FRICTION)))),
    # 114 social_trainee_group_comment_exclusion
    EventDefinition(event_id="social_trainee_group_comment_exclusion", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.38, priority=20, cooldown_days=9, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=all_of(free_slot, bound_relationship(familiarity_min=6)), director_brief="The selected trainee refers to a remark the player did not hear.", choices=(choice("ask_what_was_missed", "问问刚才错过了什么", relationship_effect(RS.CASUAL_CONTACT)), choice("remain_outside_exchange", "不追问，继续做自己的事", relationship_effect(RS.DISTANCING)))),
    # 115 social_trainee_reliability_meeting_point
    EventDefinition(event_id="social_trainee_reliability_meeting_point", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.42, priority=20, cooldown_days=8, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, slot_index_below(7)), director_brief="The selected SOCIAL trainee raises where to meet before the next slot.", choices=(choice("confirm_meeting_point", "现在一起确认碰面的地方", relationship_effect(RS.RELIABILITY_CONFIRMED)), choice("rely_on_schedule", "按正式安排走，不另外约", relationship_effect(RS.CASUAL_CONTACT)))),
    # 116 social_trainee_repair_after_shortness
    EventDefinition(event_id="social_trainee_repair_after_shortness", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.36, priority=20, cooldown_days=14, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, bound_relationship(tension_min=10)), director_brief="The current exchange ends more abruptly than intended.", choices=(choice("acknowledge_abruptness", "说明刚才自己的语气有点急", relationship_effect(RS.REPAIR)), choice("give_interaction_time", "先留一点时间，不急着解释", relationship_effect(RS.DISTANCING)))),
    # 117 social_trainee_cover_small_task
    EventDefinition(event_id="social_trainee_cover_small_task", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.38, priority=20, cooldown_days=10, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, bound_relationship(familiarity_min=35)), director_brief="The selected SOCIAL trainee asks for brief help with a scene-local task.", choices=(choice("cover_small_task", "帮她处理这个小事", relationship_effect(RS.RELIABILITY_CONFIRMED)), choice("decline_for_schedule", "因为自己的安排而婉拒", relationship_effect(RS.CASUAL_CONTACT)))),
    # 118 social_trainee_keep_minor_confidence
    EventDefinition(event_id="social_trainee_keep_minor_confidence", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.30, priority=20, cooldown_days=16, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, bound_relationship(trust_min=10)), director_brief="The selected SOCIAL trainee shares a small training-related worry.", choices=(choice("listen_privately", "听她说，并替她保留这件事", relationship_effect(RS.RELIABILITY_CONFIRMED)), choice("suggest_staff_support", "建议她去和工作人员聊聊", relationship_effect(RS.CASUAL_CONTACT)))),
    # 119 social_trainee_missed_plan_repair
    EventDefinition(event_id="social_trainee_missed_plan_repair", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.32, priority=20, cooldown_days=14, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, bound_relationship(familiarity_min=35)), director_brief="A casual suggestion made during the interaction is not followed through.", choices=(choice("make_concrete_suggestion", "重新约一个明确的时间", relationship_effect(RS.REPAIR)), choice("let_idea_lapse", "就让这个约定自然作罢", relationship_effect(RS.DISTANCING)))),
    # 120 social_trainee_mutual_check_in
    EventDefinition(event_id="social_trainee_mutual_check_in", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.40, priority=20, cooldown_days=8, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, bound_relationship(familiarity_min=35)), director_brief="The selected SOCIAL trainee asks how the player's day is going.", choices=(choice("talk_for_minutes", "认真聊几分钟", relationship_effect(RS.SHARED_POSITIVE_EXPERIENCE)), choice("quick_check_in", "简单聊两句就好", relationship_effect(RS.CASUAL_CONTACT)))),
    # 121 social_trainee_group_join_or_one_to_one
    EventDefinition(event_id="social_trainee_group_join_or_one_to_one", category=RELATIONSHIP, trigger_mode=L, tier=MINOR, interaction_mode=I, base_probability=.42, priority=20, cooldown_days=7, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, bound_relationship(familiarity_min=6)), director_brief="Other roster trainees gather while the player is with the selected target.", choices=(choice("join_small_group", "一起加入旁边的小群体", relationship_effect(RS.SHARED_POSITIVE_EXPERIENCE)), choice("keep_one_to_one", "继续两个人单独待着", relationship_effect(RS.CASUAL_CONTACT)))),
    # 122 social_trainee_decline_extra_practice
    EventDefinition(event_id="social_trainee_decline_extra_practice", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=I, base_probability=.18, priority=20, cooldown_days=6, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=all_of(company_skill_course, bound_relationship(tension_max=69)), director_brief="The selected trainee proposes one extra shared run.", choices=(choice("stay_extra_run", "留下来再练一遍", relationship_effect(RS.SHARED_POSITIVE_EXPERIENCE)), choice("leave_as_planned", "按原计划离开", relationship_effect(RS.CASUAL_CONTACT)))),
    # 123 social_trainee_bad_day_response
    EventDefinition(event_id="social_trainee_bad_day_response", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=I, base_probability=.15, priority=20, cooldown_days=8, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=bound_relationship(familiarity_min=6, tension_max=69), director_brief="The selected trainee appears less settled than usual.", choices=(choice("offer_quiet_company", "安静陪她待一会儿", relationship_effect(RS.RELIABILITY_CONFIRMED)), choice("give_acknowledged_space", "简单回应一下，然后给她空间", relationship_effect(RS.CASUAL_CONTACT)))),
    # 124 social_trainee_player_bad_day_boundary
    EventDefinition(event_id="social_trainee_player_bad_day_boundary", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=I, base_probability=.18, priority=20, cooldown_days=8, context_npc_source=SLOT, context_npc_role=TRAINEE, eligibility=all_of(SOCIAL, condition_any(condition_range("mood", 0, 34), condition_range("stress", 70))), director_brief="The selected SOCIAL trainee offers ordinary company.", choices=(choice("continue_shared_break", "继续和她一起休息", relationship_effect(RS.SHARED_POSITIVE_EXPERIENCE)), choice("end_break_quietly", "先结束这段休息，自己待一会儿", relationship_effect(RS.CASUAL_CONTACT)))),
    # 125 social_trainee_natural_distance_choice
    EventDefinition(event_id="social_trainee_natural_distance_choice", category=RELATIONSHIP, trigger_mode=P, tier=MINOR, interaction_mode=I, base_probability=.12, priority=20, cooldown_days=12, context_npc_source=ROSTER, context_npc_role=TRAINEE, eligibility=bound_relationship(familiarity_min=35, days_since_interaction_min=7), director_brief="The selected familiar trainee has not interacted with the player recently.", choices=(choice("suggest_catching_up", "主动提议最近找时间聊聊", relationship_effect(RS.REPAIR)), choice("accept_looser_rhythm", "接受现在没那么频繁的联系", relationship_effect(RS.DISTANCING)))),
)
